<a href="https://colab.research.google.com/github/MattosJ/Programas-em-Python/blob/main/numpy01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
print(np.__version__)

1.23.5


In [ ]:
array = np.array([10,20,30,40,50])
array

array([10, 20, 30, 40, 50])

In [ ]:
type(array)

numpy.ndarray

In [ ]:
duas = np.array([[10,9,8,7,6],
                [5,4,3,2,1]])
print(duas)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
tres = np.array([
    [15,14,13,12,11],
    [10,9,8,7,6],
    [5,4,3,2,1]
])

print(tres)

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
estresse = np.arange(1000000)
estresse02 = np.arange(5000000)
estresse03 = np.arange(10000000)
estresse04 = np.arange(100000000)
print(len(estresse))
print(len(estresse02))
print(len(estresse03))
print(len(estresse04))

1000000
5000000
10000000
100000000


In [ ]:
%time for i in estresse: pass

CPU times: user 147 ms, sys: 0 ns, total: 147 ms
Wall time: 156 ms


In [ ]:
%time for i in estresse02: pass

CPU times: user 377 ms, sys: 0 ns, total: 377 ms
Wall time: 380 ms


In [ ]:
%time for i in estresse03: pass

CPU times: user 740 ms, sys: 0 ns, total: 740 ms
Wall time: 742 ms


In [ ]:
%time for i in estresse04: pass

CPU times: user 9.11 s, sys: 11.8 ms, total: 9.12 s
Wall time: 9.2 s
